# Generated by Django 5.2 on 2025-04-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.CharField(max_length=3, verbose_name='Код DEF/ABC')),
                ('start', models.BigIntegerField(verbose_name='Начало диапазона')),
                ('end', models.BigIntegerField(verbose_name='Конец диапазона')),
                ('capacity', models.IntegerField(verbose_name='Емкость')),
                ('operator', models.CharField(max_length=255, verbose_name='Оператор')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('territory_gar', models.CharField(max_length=255, verbose_name='Территория ГАР')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Диапазон номеров',
                'verbose_name_plural': 'Диапазоны номеров',
                'indexes': [models.Index(fields=['abc', 'start', 'end'], name='phone_check_abc_14e2c6_idx')],
            },
        ),
    ]
